============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/stidsem4/iut/2021/controle/salome.viennet/c16_03
collected 7 items

test_16_03.py F.FFFFF                                                    [100%]

=================================== FAILURES ===================================
_____________________________ Test1603sute.test_10 _____________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
           assert False
        try:
>           Note.vider()
E           AttributeError: type object 'Note' has no attribute 'vider'

test_16_03.py:98: AttributeError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
           assert False
        try:
            Note.vider()
        except:
>           assert False
E           AssertionError: assert False

test_16_03.py:100: AssertionError
----------------------------- Captured stdout call -----------------------------
[('eleve1', 'math', 13), ('eleve1', 'physique', 15), ('eleve1', 'math', 13), ('eleve1', 'eco', 12), ('eleve1', 'eco', 13), ('eleve1', 'math', 12), ('eleve2', 'math', 13), ('eleve2', 'math', 14)]
('eleve1', 'math', 13)
13.0
12.666666666666666
La moyenne de l'élève 1 en math est :  13.0
La moyenne de l'élève 1 en physique est :  13.0
La moyenne de l'élève 1 en économie est :  13.0
La moyenne de l'élève 2 en math est :  13.5
eleve1
maths
13
eleve eleve1 matiere maths note 13
_____________________________ Test1603sute.test_4 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
>           from main import moyenne_tuples
E           ImportError: cannot import name 'moyenne_tuples' from 'main' (/home/stidsem4/iut/2021/controle/salome.viennet/main.py)

test_16_03.py:16: ImportError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
            from main import moyenne_tuples
        except ImportError:
            try:
>               from .main import moyenne_tuple as moyenne_tuples
E               ImportError: cannot import name 'moyenne_tuple' from 'c16_03.main' (/home/stidsem4/iut/2021/controle/salome.viennet/c16_03/main.py)

test_16_03.py:19: ImportError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
            from main import moyenne_tuples
        except ImportError:
            try:
                from .main import moyenne_tuple as moyenne_tuples
            except ImportError:
>               assert False, "moyenne_tuples non définie"
E               AssertionError: moyenne_tuples non définie
E               assert False

test_16_03.py:21: AssertionError
_____________________________ Test1603sute.test_5 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_5>

    def test_5(self):
        try:
>           from .main  import Note, onotes
E           ImportError: cannot import name 'onotes' from 'c16_03.main' (/home/stidsem4/iut/2021/controle/salome.viennet/c16_03/main.py)

test_16_03.py:33: ImportError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_5>

    def test_5(self):
        try:
            from .main  import Note, onotes
        except:
>           assert False
E           AssertionError: assert False

test_16_03.py:35: AssertionError
_____________________________ Test1603sute.test_6 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_6>

    def test_6(self):
>       from .main import Note, onotes
E       ImportError: cannot import name 'onotes' from 'c16_03.main' (/home/stidsem4/iut/2021/controle/salome.viennet/c16_03/main.py)

test_16_03.py:41: ImportError
_____________________________ Test1603sute.test_8 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_8>

    def test_8(self):
        try:
            from .main import Note
        except ImportError:
            assert False, "import de Note impossible"
        try:
>           from .main  import moyenne_Notes as mnotes
E           ImportError: cannot import name 'moyenne_Notes' from 'c16_03.main' (/home/stidsem4/iut/2021/controle/salome.viennet/c16_03/main.py)

test_16_03.py:71: ImportError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_8>

    def test_8(self):
        try:
            from .main import Note
        except ImportError:
            assert False, "import de Note impossible"
        try:
            from .main  import moyenne_Notes as mnotes
        except ImportError:
            try:
>               from .main  import moyenne_notes as mnotes
E               ImportError: cannot import name 'moyenne_notes' from 'c16_03.main' (/home/stidsem4/iut/2021/controle/salome.viennet/c16_03/main.py)

test_16_03.py:74: ImportError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_8>

    def test_8(self):
        try:
            from .main import Note
        except ImportError:
            assert False, "import de Note impossible"
        try:
            from .main  import moyenne_Notes as mnotes
        except ImportError:
            try:
                from .main  import moyenne_notes as mnotes
            except ImportError:
>               assert False, "La fonction moyenne_notes n'est pas définie"
E               AssertionError: La fonction moyenne_notes n'est pas définie
E               assert False

test_16_03.py:76: AssertionError
_____________________________ Test1603sute.test_9 ______________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_9>

    def test_9(self):
        try:
            from .main  import Note
        except:
           assert False
>       assert hasattr(Note, 'instances')
E       AssertionError: assert False
E        +  where False = hasattr(<class 'c16_03.main.Note'>, 'instances')

test_16_03.py:90: AssertionError
=========================== short test summary info ============================
FAILED test_16_03.py::Test1603sute::test_10 - AssertionError: assert False
FAILED test_16_03.py::Test1603sute::test_4 - AssertionError: moyenne_tuples n...
FAILED test_16_03.py::Test1603sute::test_5 - AssertionError: assert False
FAILED test_16_03.py::Test1603sute::test_6 - ImportError: cannot import name ...
FAILED test_16_03.py::Test1603sute::test_8 - AssertionError: La fonction moye...
FAILED test_16_03.py::Test1603sute::test_9 - AssertionError: assert False
========================= 6 failed, 1 passed in 0.10s ==========================
